export interface Company {
  id: string;
  name: string;
  siret: string;
  department: string;
  sector: string;
  headcount: number;
  ca: number;
  website: string;
  linkedin: string;
  naf: string;
  address: string;
  logoUrl: string;
  isHidden: boolean;
  summary?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Contact {
  id: string;
  companyId: string;
  leadId?: string;
  fullName: string;
  role: string;
  email: string;
  phone: string;
  seniority: string;
  domain: string;
  source: string;
  createdAt: Date;
}

export interface Lead {
  id: string;
  companyId: string;
  status: 'New' | 'A_TRAITER' | 'A_SUIVRE' | 'GO' | 'NO_GO';
  contactsCount: number;
  isHotSignal?: boolean;
  signalSummary?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Activity {
  id: string;
  type: string;
  entity: string;
  entityId: string;
  meta: Record<string, any>;
  createdAt: Date;
}

// Mock French companies
export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechnoSolutions Paris',
    siret: '123 456 789 00012',
    department: '75',
    sector: 'Technologie et Numérique',
    headcount: 150,
    ca: 12500000,
    website: 'https://technosolutions.fr',
    linkedin: 'https://linkedin.com/company/technosolutions',
    naf: '6201Z',
    address: '15 rue de la Tech, 75001 Paris',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=TS',
    isHidden: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Innovatech Lyon',
    siret: '234 567 890 00023',
    department: '69',
    sector: 'Services aux Entreprises',
    headcount: 85,
    ca: 8200000,
    website: 'https://innovatech-lyon.fr',
    linkedin: 'https://linkedin.com/company/innovatech',
    naf: '6202A',
    address: '42 avenue de la Soie, 69100 Lyon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=IL',
    isHidden: false,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'DataCorp Marseille',
    siret: '345 678 901 00034',
    department: '13',
    sector: 'Technologie et Numérique',
    headcount: 120,
    ca: 15600000,
    website: 'https://datacorp.fr',
    linkedin: 'https://linkedin.com/company/datacorp',
    naf: '6311Z',
    address: '8 boulevard du Prado, 13008 Marseille',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DC',
    isHidden: false,
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'CloudServ Toulouse',
    siret: '456 789 012 00045',
    department: '31',
    sector: 'Technologie et Numérique',
    headcount: 200,
    ca: 22000000,
    website: 'https://cloudserv.fr',
    linkedin: 'https://linkedin.com/company/cloudserv',
    naf: '6311Z',
    address: '25 allée Jean Jaurès, 31000 Toulouse',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CS',
    isHidden: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    name: 'Digital France Nantes',
    siret: '567 890 123 00056',
    department: '44',
    sector: 'Services aux Entreprises',
    headcount: 95,
    ca: 7800000,
    website: 'https://digitalfrance.fr',
    linkedin: 'https://linkedin.com/company/digitalfrance',
    naf: '7311Z',
    address: '10 quai de la Fosse, 44000 Nantes',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DF',
    isHidden: false,
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'SecurIT Bordeaux',
    siret: '678 901 234 00067',
    department: '33',
    sector: 'Technologie et Numérique',
    headcount: 110,
    ca: 13500000,
    website: 'https://securit.fr',
    linkedin: 'https://linkedin.com/company/securit',
    naf: '6202A',
    address: '18 cours de l\'Intendance, 33000 Bordeaux',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SB',
    isHidden: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '7',
    name: 'AIVision Lille',
    siret: '789 012 345 00078',
    department: '59',
    sector: 'Technologie et Numérique',
    headcount: 75,
    ca: 9200000,
    website: 'https://aivision.fr',
    linkedin: 'https://linkedin.com/company/aivision',
    naf: '6201Z',
    address: '30 rue Nationale, 59000 Lille',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AI',
    isHidden: false,
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '8',
    name: 'Construction Plus Strasbourg',
    siret: '890 123 456 00089',
    department: '67',
    sector: 'BTP et Construction',
    headcount: 160,
    ca: 25400000,
    website: 'https://constructionplus.fr',
    linkedin: 'https://linkedin.com/company/constructionplus',
    naf: '4120A',
    address: '5 place Kléber, 67000 Strasbourg',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CP',
    isHidden: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '9',
    name: 'TransportExpress Nice',
    siret: '901 234 567 00090',
    department: '06',
    sector: 'Transport et Logistique',
    headcount: 245,
    ca: 34200000,
    website: 'https://transportexpress.fr',
    linkedin: 'https://linkedin.com/company/transportexpress',
    naf: '4941A',
    address: '12 promenade des Anglais, 06000 Nice',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=TE',
    isHidden: false,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '10',
    name: 'EcomRetail Rennes',
    siret: '012 345 678 00001',
    department: '35',
    sector: 'Commerce et Distribution',
    headcount: 130,
    ca: 18000000,
    website: 'https://ecomretail.fr',
    linkedin: 'https://linkedin.com/company/ecomretail',
    naf: '4791B',
    address: '20 rue du Capitaine Maignan, 35000 Rennes',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ER',
    isHidden: false,
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: '11',
    name: 'GreenEnergy Grenoble',
    siret: '123 456 789 00111',
    department: '38',
    sector: 'Énergie et Environnement',
    headcount: 90,
    ca: 10500000,
    website: 'https://greenenergy-grenoble.fr',
    linkedin: 'https://linkedin.com/company/greenenergy',
    naf: '3511Z',
    address: '14 cours Jean Jaurès, 38000 Grenoble',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=GE',
    isHidden: false,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '12',
    name: 'BanqueAssur Montpellier',
    siret: '234 567 890 00122',
    department: '34',
    sector: 'Finance et Assurance',
    headcount: 105,
    ca: 14800000,
    website: 'https://banqueassur-montpellier.fr',
    linkedin: 'https://linkedin.com/company/banqueassur',
    naf: '6419Z',
    address: '8 rue de la Loge, 34000 Montpellier',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=BA',
    isHidden: false,
    createdAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: '13',
    name: 'CliniqueSanté Rouen',
    siret: '345 678 901 00133',
    department: '76',
    sector: 'Santé et Social',
    headcount: 155,
    ca: 26300000,
    website: 'https://cliniquesante-rouen.fr',
    linkedin: 'https://linkedin.com/company/cliniquesante',
    naf: '8610Z',
    address: '22 rue Jeanne d\'Arc, 76000 Rouen',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CS',
    isHidden: false,
    createdAt: new Date('2024-01-27'),
    updatedAt: new Date('2024-01-27'),
  },
  {
    id: '14',
    name: 'LogisTrans Reims',
    siret: '456 789 012 00144',
    department: '51',
    sector: 'Transport et Logistique',
    headcount: 180,
    ca: 24000000,
    website: 'https://logistrans.fr',
    linkedin: 'https://linkedin.com/company/logistrans',
    naf: '5229A',
    address: '35 boulevard Lundy, 51100 Reims',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=LT',
    isHidden: false,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '15',
    name: 'IndustrieMetaux Dijon',
    siret: '567 890 123 00155',
    department: '21',
    sector: 'Industrie',
    headcount: 270,
    ca: 48900000,
    website: 'https://industriemetaux-dijon.fr',
    linkedin: 'https://linkedin.com/company/industriemetaux',
    naf: '2561Z',
    address: '11 rue de la Liberté, 21000 Dijon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=IM',
    isHidden: false,
    createdAt: new Date('2024-01-29'),
    updatedAt: new Date('2024-01-29'),
  },
  {
    id: '16',
    name: 'FormationPro Angers',
    siret: '678 901 234 00166',
    department: '49',
    sector: 'Éducation et Formation',
    headcount: 65,
    ca: 7200000,
    website: 'https://formationpro-angers.fr',
    linkedin: 'https://linkedin.com/company/formationpro',
    naf: '8559A',
    address: '9 place du Ralliement, 49000 Angers',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=FP',
    isHidden: false,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: '17',
    name: 'AgriTech Le Mans',
    siret: '789 012 345 00177',
    department: '72',
    sector: 'Agriculture et Agroalimentaire',
    headcount: 180,
    ca: 31200000,
    website: 'https://agritech.fr',
    linkedin: 'https://linkedin.com/company/agritech',
    naf: '1089Z',
    address: '16 avenue François Mitterrand, 72000 Le Mans',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AT',
    isHidden: false,
    createdAt: new Date('2024-01-31'),
    updatedAt: new Date('2024-01-31'),
  },
  {
    id: '18',
    name: 'HôtelResort Tours',
    siret: '890 123 456 00188',
    department: '37',
    sector: 'Tourisme et Hôtellerie',
    headcount: 150,
    ca: 15800000,
    website: 'https://hotelresort-tours.fr',
    linkedin: 'https://linkedin.com/company/hotelresort',
    naf: '5510Z',
    address: '7 place Jean Jaurès, 37000 Tours',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=HR',
    isHidden: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '19',
    name: 'ConseilStratégie Amiens',
    siret: '901 234 567 00199',
    department: '80',
    sector: 'Services aux Entreprises',
    headcount: 95,
    ca: 12800000,
    website: 'https://conseilstrategie.fr',
    linkedin: 'https://linkedin.com/company/conseilstrategie',
    naf: '7022Z',
    address: '4 rue des Trois Cailloux, 80000 Amiens',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CS2',
    isHidden: false,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    id: '20',
    name: 'BâtimentRénov Clermont',
    siret: '012 345 678 00200',
    department: '63',
    sector: 'BTP et Construction',
    headcount: 215,
    ca: 36500000,
    website: 'https://batimentrenov-clermont.fr',
    linkedin: 'https://linkedin.com/company/batimentrenov',
    naf: '4120B',
    address: '19 avenue des États-Unis, 63000 Clermont-Ferrand',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=BR',
    isHidden: false,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: '21',
    name: 'TechSolutions Besançon',
    siret: '123 456 789 00211',
    department: '25',
    sector: 'Technologie et Numérique',
    headcount: 40,
    ca: 4500000,
    website: 'https://techsolutions-besancon.fr',
    linkedin: 'https://linkedin.com/company/techsolutions',
    naf: '6201Z',
    address: '13 rue de la République, 25000 Besançon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=TS2',
    isHidden: false,
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: '22',
    name: 'MagasinDistrib Orléans',
    siret: '234 567 890 00222',
    department: '45',
    sector: 'Commerce et Distribution',
    headcount: 188,
    ca: 30200000,
    website: 'https://magasindistrib-orleans.fr',
    linkedin: 'https://linkedin.com/company/magasindistrib',
    naf: '4711D',
    address: '21 place du Martroi, 45000 Orléans',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MD',
    isHidden: false,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '23',
    name: 'ÉcoleFormation Caen',
    siret: '345 678 901 00233',
    department: '14',
    sector: 'Éducation et Formation',
    headcount: 52,
    ca: 5900000,
    website: 'https://ecoleformation-caen.fr',
    linkedin: 'https://linkedin.com/company/ecoleformation',
    naf: '8559A',
    address: '6 rue Saint-Pierre, 14000 Caen',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=EF',
    isHidden: false,
    createdAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-06'),
  },
  {
    id: '24',
    name: 'AssuranceVie Limoges',
    siret: '456 789 012 00244',
    department: '87',
    sector: 'Finance et Assurance',
    headcount: 72,
    ca: 18600000,
    website: 'https://assurancevie.fr',
    linkedin: 'https://linkedin.com/company/assurancevie',
    naf: '6512Z',
    address: '10 place de la République, 87000 Limoges',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AV',
    isHidden: false,
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
  },
  {
    id: '25',
    name: 'AgroAlimentaire Poitiers',
    siret: '567 890 123 00255',
    department: '86',
    sector: 'Agriculture et Agroalimentaire',
    headcount: 298,
    ca: 51900000,
    website: 'https://agroalimentaire.fr',
    linkedin: 'https://linkedin.com/company/agroalimentaire',
    naf: '1085Z',
    address: '3 place du Maréchal Leclerc, 86000 Poitiers',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AA',
    isHidden: false,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
];

// Mock contacts for some companies
export const mockContacts: Contact[] = [
  // Contacts for TechnoSolutions Paris (id: 1)
  {
    id: 'c1',
    companyId: '1',
    fullName: 'Sophie Martin',
    role: 'Directrice Commerciale',
    email: 's.martin@technosolutions.fr',
    phone: '+33 1 42 86 95 00',
    seniority: 'Senior',
    domain: 'Commercial',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'c2',
    companyId: '1',
    fullName: 'Thomas Dubois',
    role: 'Directeur Marketing',
    email: 't.dubois@technosolutions.fr',
    phone: '+33 1 42 86 95 01',
    seniority: 'Senior',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'c3',
    companyId: '1',
    fullName: 'Marie Leroy',
    role: 'Directrice Générale',
    email: 'm.leroy@technosolutions.fr',
    phone: '+33 1 42 86 95 02',
    seniority: 'C-Level',
    domain: 'Direction',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  // Contacts for Innovatech Lyon (id: 2)
  {
    id: 'c4',
    companyId: '2',
    fullName: 'Pierre Bernard',
    role: 'Responsable Commercial',
    email: 'p.bernard@innovatech-lyon.fr',
    phone: '+33 4 78 62 35 00',
    seniority: 'Mid-Level',
    domain: 'Commercial',
    source: 'Website',
    createdAt: new Date('2024-02-02'),
  },
  {
    id: 'c5',
    companyId: '2',
    fullName: 'Julie Petit',
    role: 'Chef de Projet Marketing',
    email: 'j.petit@innovatech-lyon.fr',
    phone: '+33 4 78 62 35 01',
    seniority: 'Mid-Level',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-02'),
  },
  // Contacts for DataCorp Marseille (id: 3)
  {
    id: 'c6',
    companyId: '3',
    fullName: 'Laurent Moreau',
    role: 'CEO',
    email: 'l.moreau@datacorp.fr',
    phone: '+33 4 91 15 82 00',
    seniority: 'C-Level',
    domain: 'Direction',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c7',
    companyId: '3',
    fullName: 'Isabelle Simon',
    role: 'Directrice des Opérations',
    email: 'i.simon@datacorp.fr',
    phone: '+33 4 91 15 82 01',
    seniority: 'C-Level',
    domain: 'Opérations',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c8',
    companyId: '3',
    fullName: 'Nicolas Laurent',
    role: 'Commercial Senior',
    email: 'n.laurent@datacorp.fr',
    phone: '+33 4 91 15 82 02',
    seniority: 'Senior',
    domain: 'Commercial',
    source: 'Website',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c9',
    companyId: '3',
    fullName: 'Camille Girard',
    role: 'Responsable Marketing Digital',
    email: 'c.girard@datacorp.fr',
    phone: '+33 4 91 15 82 03',
    seniority: 'Mid-Level',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
];

// Mock leads
export const mockLeads: Lead[] = [
  {
    id: 'l1',
    companyId: '1',
    status: 'New',
    contactsCount: 3,
    isHotSignal: true,
    signalSummary: 'L\'entreprise a récemment annoncé un projet de transformation digitale de 2M€. Le directeur IT cherche activement des solutions cloud.',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'l2',
    companyId: '2',
    status: 'A_TRAITER',
    contactsCount: 2,
    isHotSignal: true,
    signalSummary: 'Levée de fonds de 5M€ annoncée. Recrutement de 10 profils tech en cours. Budget marketing en forte hausse.',
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    id: 'l3',
    companyId: '3',
    status: 'A_SUIVRE',
    contactsCount: 4,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: 'l4',
    companyId: '6',
    status: 'GO',
    contactsCount: 0,
    isHotSignal: true,
    signalSummary: 'Ouverture d\'un nouveau site à Paris. L\'entreprise recherche des partenaires pour la sécurisation de ses infrastructures.',
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: 'l5',
    companyId: '8',
    status: 'New',
    contactsCount: 0,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'l6',
    companyId: '9',
    status: 'New',
    contactsCount: 0,
    isHotSignal: true,
    signalSummary: 'Expansion nationale en cours. L\'entreprise ouvre 5 nouvelles agences et recrute massivement dans le transport et la logistique.',
    createdAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-06'),
  },
  {
    id: 'l7',
    companyId: '18',
    status: 'New',
    contactsCount: 0,
    isHotSignal: true,
    signalSummary: 'Investissement de 3M€ dans la digitalisation de l\'établissement. Recherche active de solutions CRM et de gestion hôtelière.',
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
  },
];

// Mock activities
export const mockActivities: Activity[] = [
  {
    id: 'a1',
    type: 'LEAD_CREATED',
    entity: 'Lead',
    entityId: 'l1',
    meta: { companyName: 'TechnoSolutions Paris', status: 'New' },
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'a2',
    type: 'CONTACT_ADDED',
    entity: 'Contact',
    entityId: 'c1',
    meta: { companyName: 'TechnoSolutions Paris', contactName: 'Sophie Martin' },
    createdAt: new Date('2024-02-01'),
  },
];
