export interface Company {
  id: string;
  name: string;
  siret: string;
  department: string;
  sector: string;
  headcount: number;
  ca: number;
  website: string;
  linkedin: string;
  naf: string;
  address: string;
  logoUrl: string;
  isHidden: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Contact {
  id: string;
  companyId: string;
  leadId?: string;
  fullName: string;
  role: string;
  email: string;
  phone: string;
  seniority: string;
  domain: string;
  source: string;
  createdAt: Date;
}

export interface Lead {
  id: string;
  companyId: string;
  status: 'New' | 'A_TRAITER' | 'A_SUIVRE' | 'GO' | 'NO_GO';
  contactsCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Activity {
  id: string;
  type: string;
  entity: string;
  entityId: string;
  meta: Record<string, any>;
  createdAt: Date;
}

// Mock French companies
export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechnoSolutions Paris',
    siret: '123 456 789 00012',
    department: '75',
    sector: 'Technologies de l\'information',
    headcount: 150,
    ca: 12500000,
    website: 'https://technosolutions.fr',
    linkedin: 'https://linkedin.com/company/technosolutions',
    naf: '6201Z',
    address: '15 rue de la Tech, 75001 Paris',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=TS',
    isHidden: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Innovatech Lyon',
    siret: '234 567 890 00023',
    department: '69',
    sector: 'Conseil en technologies',
    headcount: 85,
    ca: 8200000,
    website: 'https://innovatech-lyon.fr',
    linkedin: 'https://linkedin.com/company/innovatech',
    naf: '6202A',
    address: '42 avenue de la Soie, 69100 Lyon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=IL',
    isHidden: false,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'DataCorp Marseille',
    siret: '345 678 901 00034',
    department: '13',
    sector: 'Big Data & Analytics',
    headcount: 120,
    ca: 15600000,
    website: 'https://datacorp.fr',
    linkedin: 'https://linkedin.com/company/datacorp',
    naf: '6311Z',
    address: '8 boulevard du Prado, 13008 Marseille',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DC',
    isHidden: false,
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'CloudServ Toulouse',
    siret: '456 789 012 00045',
    department: '31',
    sector: 'Cloud Computing',
    headcount: 200,
    ca: 22000000,
    website: 'https://cloudserv.fr',
    linkedin: 'https://linkedin.com/company/cloudserv',
    naf: '6311Z',
    address: '25 allée Jean Jaurès, 31000 Toulouse',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CS',
    isHidden: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    name: 'Digital France Nantes',
    siret: '567 890 123 00056',
    department: '44',
    sector: 'Marketing Digital',
    headcount: 95,
    ca: 7800000,
    website: 'https://digitalfrance.fr',
    linkedin: 'https://linkedin.com/company/digitalfrance',
    naf: '7311Z',
    address: '10 quai de la Fosse, 44000 Nantes',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DF',
    isHidden: false,
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'SecurIT Bordeaux',
    siret: '678 901 234 00067',
    department: '33',
    sector: 'Cybersécurité',
    headcount: 110,
    ca: 13500000,
    website: 'https://securit.fr',
    linkedin: 'https://linkedin.com/company/securit',
    naf: '6202A',
    address: '18 cours de l\'Intendance, 33000 Bordeaux',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SB',
    isHidden: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '7',
    name: 'AIVision Lille',
    siret: '789 012 345 00078',
    department: '59',
    sector: 'Intelligence Artificielle',
    headcount: 75,
    ca: 9200000,
    website: 'https://aivision.fr',
    linkedin: 'https://linkedin.com/company/aivision',
    naf: '6201Z',
    address: '30 rue Nationale, 59000 Lille',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AI',
    isHidden: false,
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '8',
    name: 'WebFactory Strasbourg',
    siret: '890 123 456 00089',
    department: '67',
    sector: 'Développement Web',
    headcount: 60,
    ca: 5400000,
    website: 'https://webfactory.fr',
    linkedin: 'https://linkedin.com/company/webfactory',
    naf: '6201Z',
    address: '5 place Kléber, 67000 Strasbourg',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=WF',
    isHidden: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '9',
    name: 'MobileTech Nice',
    siret: '901 234 567 00090',
    department: '06',
    sector: 'Applications Mobiles',
    headcount: 45,
    ca: 4200000,
    website: 'https://mobiletech-nice.fr',
    linkedin: 'https://linkedin.com/company/mobiletech',
    naf: '6201Z',
    address: '12 promenade des Anglais, 06000 Nice',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MT',
    isHidden: false,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '10',
    name: 'EcomSolutions Rennes',
    siret: '012 345 678 00001',
    department: '35',
    sector: 'E-commerce',
    headcount: 130,
    ca: 18000000,
    website: 'https://ecomsolutions.fr',
    linkedin: 'https://linkedin.com/company/ecomsolutions',
    naf: '6312Z',
    address: '20 rue du Capitaine Maignan, 35000 Rennes',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=ES',
    isHidden: false,
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: '11',
    name: 'GreenTech Grenoble',
    siret: '123 456 789 00111',
    department: '38',
    sector: 'Technologies Vertes',
    headcount: 90,
    ca: 10500000,
    website: 'https://greentech-grenoble.fr',
    linkedin: 'https://linkedin.com/company/greentech',
    naf: '7112B',
    address: '14 cours Jean Jaurès, 38000 Grenoble',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=GT',
    isHidden: false,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '12',
    name: 'FinTech Montpellier',
    siret: '234 567 890 00122',
    department: '34',
    sector: 'Technologies Financières',
    headcount: 105,
    ca: 14800000,
    website: 'https://fintech-montpellier.fr',
    linkedin: 'https://linkedin.com/company/fintech-mtp',
    naf: '6619B',
    address: '8 rue de la Loge, 34000 Montpellier',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=FM',
    isHidden: false,
    createdAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: '13',
    name: 'MediaPro Rouen',
    siret: '345 678 901 00133',
    department: '76',
    sector: 'Production Audiovisuelle',
    headcount: 55,
    ca: 6300000,
    website: 'https://mediapro-rouen.fr',
    linkedin: 'https://linkedin.com/company/mediapro',
    naf: '5911A',
    address: '22 rue Jeanne d\'Arc, 76000 Rouen',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=MP',
    isHidden: false,
    createdAt: new Date('2024-01-27'),
    updatedAt: new Date('2024-01-27'),
  },
  {
    id: '14',
    name: 'LogisTech Reims',
    siret: '456 789 012 00144',
    department: '51',
    sector: 'Logistique & Transport',
    headcount: 180,
    ca: 24000000,
    website: 'https://logistech.fr',
    linkedin: 'https://linkedin.com/company/logistech',
    naf: '5229A',
    address: '35 boulevard Lundy, 51100 Reims',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=LT',
    isHidden: false,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '15',
    name: 'HealthIT Dijon',
    siret: '567 890 123 00155',
    department: '21',
    sector: 'Technologies Santé',
    headcount: 70,
    ca: 8900000,
    website: 'https://healthit-dijon.fr',
    linkedin: 'https://linkedin.com/company/healthit',
    naf: '6201Z',
    address: '11 rue de la Liberté, 21000 Dijon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=HI',
    isHidden: false,
    createdAt: new Date('2024-01-29'),
    updatedAt: new Date('2024-01-29'),
  },
  {
    id: '16',
    name: 'IoT Angers',
    siret: '678 901 234 00166',
    department: '49',
    sector: 'Internet des Objets',
    headcount: 65,
    ca: 7200000,
    website: 'https://iot-angers.fr',
    linkedin: 'https://linkedin.com/company/iot-angers',
    naf: '6201Z',
    address: '9 place du Ralliement, 49000 Angers',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=IA',
    isHidden: false,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: '17',
    name: 'RoboticsLab Le Mans',
    siret: '789 012 345 00177',
    department: '72',
    sector: 'Robotique',
    headcount: 80,
    ca: 11200000,
    website: 'https://roboticslab.fr',
    linkedin: 'https://linkedin.com/company/roboticslab',
    naf: '7112B',
    address: '16 avenue François Mitterrand, 72000 Le Mans',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=RL',
    isHidden: false,
    createdAt: new Date('2024-01-31'),
    updatedAt: new Date('2024-01-31'),
  },
  {
    id: '18',
    name: 'GameStudio Tours',
    siret: '890 123 456 00188',
    department: '37',
    sector: 'Jeux Vidéo',
    headcount: 50,
    ca: 5800000,
    website: 'https://gamestudio-tours.fr',
    linkedin: 'https://linkedin.com/company/gamestudio',
    naf: '5821Z',
    address: '7 place Jean Jaurès, 37000 Tours',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=GS',
    isHidden: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '19',
    name: 'DataSecure Amiens',
    siret: '901 234 567 00199',
    department: '80',
    sector: 'Sécurité des Données',
    headcount: 95,
    ca: 12800000,
    website: 'https://datasecure.fr',
    linkedin: 'https://linkedin.com/company/datasecure',
    naf: '6202A',
    address: '4 rue des Trois Cailloux, 80000 Amiens',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=DS',
    isHidden: false,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    id: '20',
    name: 'SmartCity Clermont',
    siret: '012 345 678 00200',
    department: '63',
    sector: 'Smart Cities',
    headcount: 115,
    ca: 16500000,
    website: 'https://smartcity-clermont.fr',
    linkedin: 'https://linkedin.com/company/smartcity',
    naf: '7112B',
    address: '19 avenue des États-Unis, 63000 Clermont-Ferrand',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=SC',
    isHidden: false,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: '21',
    name: 'VRTech Besançon',
    siret: '123 456 789 00211',
    department: '25',
    sector: 'Réalité Virtuelle',
    headcount: 40,
    ca: 4500000,
    website: 'https://vrtech-besancon.fr',
    linkedin: 'https://linkedin.com/company/vrtech',
    naf: '6201Z',
    address: '13 rue de la République, 25000 Besançon',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=VR',
    isHidden: false,
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: '22',
    name: 'CloudData Orléans',
    siret: '234 567 890 00222',
    department: '45',
    sector: 'Stockage Cloud',
    headcount: 88,
    ca: 10200000,
    website: 'https://clouddata-orleans.fr',
    linkedin: 'https://linkedin.com/company/clouddata',
    naf: '6311Z',
    address: '21 place du Martroi, 45000 Orléans',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CD',
    isHidden: false,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '23',
    name: 'AppMobile Caen',
    siret: '345 678 901 00233',
    department: '14',
    sector: 'Applications Mobiles',
    headcount: 52,
    ca: 5900000,
    website: 'https://appmobile-caen.fr',
    linkedin: 'https://linkedin.com/company/appmobile',
    naf: '6201Z',
    address: '6 rue Saint-Pierre, 14000 Caen',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AM',
    isHidden: false,
    createdAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-06'),
  },
  {
    id: '24',
    name: 'CyberGuard Limoges',
    siret: '456 789 012 00244',
    department: '87',
    sector: 'Cybersécurité',
    headcount: 72,
    ca: 8600000,
    website: 'https://cyberguard.fr',
    linkedin: 'https://linkedin.com/company/cyberguard',
    naf: '6202A',
    address: '10 place de la République, 87000 Limoges',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=CG',
    isHidden: false,
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
  },
  {
    id: '25',
    name: 'TechConsulting Poitiers',
    siret: '567 890 123 00255',
    department: '86',
    sector: 'Conseil IT',
    headcount: 98,
    ca: 11900000,
    website: 'https://techconsulting.fr',
    linkedin: 'https://linkedin.com/company/techconsulting',
    naf: '6202A',
    address: '3 place du Maréchal Leclerc, 86000 Poitiers',
    logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=TC',
    isHidden: false,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
];

// Mock contacts for some companies
export const mockContacts: Contact[] = [
  // Contacts for TechnoSolutions Paris (id: 1)
  {
    id: 'c1',
    companyId: '1',
    fullName: 'Sophie Martin',
    role: 'Directrice Commerciale',
    email: 's.martin@technosolutions.fr',
    phone: '+33 1 42 86 95 00',
    seniority: 'Senior',
    domain: 'Commercial',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'c2',
    companyId: '1',
    fullName: 'Thomas Dubois',
    role: 'Directeur Marketing',
    email: 't.dubois@technosolutions.fr',
    phone: '+33 1 42 86 95 01',
    seniority: 'Senior',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'c3',
    companyId: '1',
    fullName: 'Marie Leroy',
    role: 'Directrice Générale',
    email: 'm.leroy@technosolutions.fr',
    phone: '+33 1 42 86 95 02',
    seniority: 'C-Level',
    domain: 'Direction',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-01'),
  },
  // Contacts for Innovatech Lyon (id: 2)
  {
    id: 'c4',
    companyId: '2',
    fullName: 'Pierre Bernard',
    role: 'Responsable Commercial',
    email: 'p.bernard@innovatech-lyon.fr',
    phone: '+33 4 78 62 35 00',
    seniority: 'Mid-Level',
    domain: 'Commercial',
    source: 'Website',
    createdAt: new Date('2024-02-02'),
  },
  {
    id: 'c5',
    companyId: '2',
    fullName: 'Julie Petit',
    role: 'Chef de Projet Marketing',
    email: 'j.petit@innovatech-lyon.fr',
    phone: '+33 4 78 62 35 01',
    seniority: 'Mid-Level',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-02'),
  },
  // Contacts for DataCorp Marseille (id: 3)
  {
    id: 'c6',
    companyId: '3',
    fullName: 'Laurent Moreau',
    role: 'CEO',
    email: 'l.moreau@datacorp.fr',
    phone: '+33 4 91 15 82 00',
    seniority: 'C-Level',
    domain: 'Direction',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c7',
    companyId: '3',
    fullName: 'Isabelle Simon',
    role: 'Directrice des Opérations',
    email: 'i.simon@datacorp.fr',
    phone: '+33 4 91 15 82 01',
    seniority: 'C-Level',
    domain: 'Opérations',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c8',
    companyId: '3',
    fullName: 'Nicolas Laurent',
    role: 'Commercial Senior',
    email: 'n.laurent@datacorp.fr',
    phone: '+33 4 91 15 82 02',
    seniority: 'Senior',
    domain: 'Commercial',
    source: 'Website',
    createdAt: new Date('2024-02-03'),
  },
  {
    id: 'c9',
    companyId: '3',
    fullName: 'Camille Girard',
    role: 'Responsable Marketing Digital',
    email: 'c.girard@datacorp.fr',
    phone: '+33 4 91 15 82 03',
    seniority: 'Mid-Level',
    domain: 'Marketing',
    source: 'LinkedIn',
    createdAt: new Date('2024-02-03'),
  },
];

// Mock leads
export const mockLeads: Lead[] = [
  {
    id: 'l1',
    companyId: '1',
    status: 'New',
    contactsCount: 3,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'l2',
    companyId: '2',
    status: 'A_TRAITER',
    contactsCount: 2,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    id: 'l3',
    companyId: '3',
    status: 'A_SUIVRE',
    contactsCount: 4,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: 'l4',
    companyId: '6',
    status: 'GO',
    contactsCount: 0,
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: 'l5',
    companyId: '8',
    status: 'New',
    contactsCount: 0,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
];

// Mock activities
export const mockActivities: Activity[] = [
  {
    id: 'a1',
    type: 'LEAD_CREATED',
    entity: 'Lead',
    entityId: 'l1',
    meta: { companyName: 'TechnoSolutions Paris', status: 'New' },
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'a2',
    type: 'CONTACT_ADDED',
    entity: 'Contact',
    entityId: 'c1',
    meta: { companyName: 'TechnoSolutions Paris', contactName: 'Sophie Martin' },
    createdAt: new Date('2024-02-01'),
  },
];
